### ISSUE TITLE
Provide typings

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whs.js#189]
Typescript developers would benefit in having typings for whs. There are already some [typings](https://www.npmjs.com/package/@types/three) for `three.js`.
See [best practice](http://definitelytyped.org/guides/best-practices.html) to write type definitions.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@hirako2000 how to implement?

**Comment by hirako2000** [comment]
Creating typings, [definitelytyped](http://definitelytyped.org/guides/creating.html)

**Comment by ElectrcNINJA** [comment]
I can help with this; It would be very nice to have with any project I would use WHS in.

**Comment by sasha240100** [comment]
@ElectrcNINJA would be awesome cause I am 0 at typescript. Make a fork/branch with a name "#189", work there and do a PR

**Comment by thejmazz** [comment]
typescript over flow is a good call I think

**Comment by thejmazz** [comment]
How well does TS handle static properties on a class?

Can it autosuggest a class's static properties in IDEs?

Could maybe annotate components with how they expose bridges with something like

```javascript
static bridgeTypes = [ ' geometry', 'material', 'mesh', 'onWrap' ]
```

**Comment by hirako2000** [comment]
from my little experience with TS, types are perfectly supported, so long as the typings are well defined (and installed) for dep libraries written in JS of course.
IDEs commonly have support for TS autocompletion etc. - excellent support on Atom and VisualCode.

Best is to see int action and appreciate how good it can be to have types available, especially when learning how to use unfamiliar APIs.

If you setup a skeleton typescript project, import a poplar library such as lodash. insteall definitlytyped and lodash's typings.

**Comment by zored** [comment]
@sasha240100 Waiting for typings. 😄 Have you seen that you can [use `"types": "./typings/wts.d.ts"` in `package.json`](http://stackoverflow.com/a/39998720/1611395) to avoid `@types/...` dependency?

**Comment by hirako2000** [comment]
Zored, we do need typings, we've been busy doing other things in the mean time, and would love someone having typings definitions experience or knowledge to take the lead on this. 
The typescript boilerplate is set up with typings for other frameworks, including three.js, it would be a nice place to experiment with some basic WHS definitions.

Are you able to give us a hand with this?

**Comment by zored** [comment]
@hirako2000 ok, I'll write definitions and I'll create pull-request in several days. Currently I try to adapt `dts-gen` to automate typings generation. Otherwise I'll create them manually. There will be `./typings/*.d.ts` in project root similar to [`@types/three`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/three). But without tests for now that are just checking input/output types.

**Comment by hirako2000** [comment]
I'v started adding type definitions, starting with Core.
Would it make sense to fork [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) under WhitestormJS and contribute there?
We can then make pull requests, it will publish to npm once they get merged by the dt team.

**Comment by d-ph** [comment]
@hirako2000 Please don't contribute to DT. Instead add the types directly to this project's repo (as @zored said). This is the recommended way of providing typings for js projects.

See [vuejs](https://github.com/vuejs/vue) for reference:
1. `types/index.d.ts`: [link](https://github.com/vuejs/vue/blob/dev/types/index.d.ts)
2. In `package.json` mention the `types/index.d.ts` in the `typings` field: [link](https://github.com/vuejs/vue/blob/8d56a49/package.json#L8)

This way:
1. Devs of whitestorm.js don't need to wait for DT to merge and publish typings changes.
2. Typescript users of whitestorm.js will get the typings automagically after they `npm install whs`

**Comment by hirako2000** [comment]
thanks a lot for the input @d-ph, will do that

**Comment by hirako2000** [comment]
We few types are added and this Issue became a snowball as it included jsDoc setup etc.
Types continued with issue #267 
We will have multiple issues to get all types provided by `whs`
