### ISSUE TITLE
Make a separate WHS.Curve component

### ISSUE THREAD

**Issue by sasha240100** [WhitestormJS/whs.js#228]
In issue #217 we have a new `WHS.Line` described. Since it shouldn't support curves, we have to make a new `WHS.Curve` component.

**Location:** `src/components/meshes/Curve.js`

**Concept**

```javascript
const curve = new WHS.Curve({
  geometry: {
    curve: new THREE.Curve(),
    points: 50
  },
  
  // ...
});
```

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
[THREE.Curve](https://threejs.org/docs/#api/extras/core/Curve) is an abstract object.
There are numerous three.js native type of curves. Not sure what curve to provide there as a component.

**Comment by sasha240100** [comment]
Close?

**Comment by hirako2000** [comment]
yep I don't think it's a priority as we could create hundreds of components. people can create their own already.

**Comment by sasha240100** [comment]
Deprecated
