### ISSUE TITLE
Provide Typings for Cameras

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whs.js#269]
the different types of cameras needs their typings.
The CameraComponent also needs completed with parameter types to be inherited

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
Continued with #271

**Comment by sasha240100** [comment]
@hirako2000 Thanks!
