### ISSUE TITLE
Integrate tsd-jsdoc into whs

### ISSUE THREAD

**Issue by ChaseWhite3** [WhitestormJS/whs.js#291]
Integrate tsd-jsdoc npm module into whs to automatically generate typescript files from jsdocs.

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [x] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by ChaseWhite3** [comment]
This is too experimental for now.

**Comment by sasha240100** [comment]
@ChaseWhite3 Doesn't work?
