### ISSUE TITLE
Use travis CI to publish to npm

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whs.js#292]
Cumbersome to publish from local machines.
Travis should publish to npm new versions of `whs`.

See how: https://docs.travis-ci.com/user/deployment/npm/

###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [x] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by hirako2000** [comment]
added the config, but my encrypted API token doesn't seem found. strange doc from Travis.
Maybe using a config variable would be easier, they say to put it in the travis file and simply encrypt it. but I see you do it differently for snyk and surge @sasha240100 .
See if you can use your own api key and get it to work.
Right now it tries to build and publish but fails with the token.

Travis will only try to deploy/publish to npmjs if it sees a tag pushed.

**Comment by hirako2000** [comment]
Deploy works, Travis will publish to npmjs on new tags applied to the `dev` branch.
Travis currently won't commit/push the built files. this step remains having to be done manually, same for the release notes.

Closing this now. Next step would be to cover those two tasks:
- Push built files
- Automatically generate release notes from closed issues and PRs.

As part of different issues.

**Comment by sasha240100** [comment]
@hirako2000 Maybe better to make the same only for `master` branch? I always merge dev to it after each release

**Comment by hirako2000** [comment]
Yes that would make sense, I didn't know you released from master. that's the correct thing to do ;)
