### ISSUE TITLE
postprocessing and redux deps are missing

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whs.js#305]
`postprocessing` is used by the postprocessing module, but is not declared in deps.
`redux` is now used to keep the store, but also is not declared in deps.

They should not be in devDependency, but in dependency.
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [x] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details>

**Comment by sasha240100** [comment]
@hirako2000 you fix?

**Comment by hirako2000** [comment]
yea should be fixed. merge the PR.

**Comment by sasha240100** [comment]
@hirako2000 merged
