### ISSUE TITLE
Add module for sound system

### ISSUE THREAD

**Issue by jackdalton** [WhitestormJS/whs.js#77]
One thing that WhitestormJS is currently lacking is something to take care of sound that doesn't require the user to fool around with the [web audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API).

**Comment by sasha240100** [comment]
@jackdalton Will be soon implemented as a module, i think...

**Comment by hirako2000** [comment]
work in progress. @jackdalton , add some ideas about the module API if you have suggestions.

**Comment by sasha240100** [comment]
@hirako2000 Push your work

**Comment by hirako2000** [comment]
whs-audio-module is not published on npm yet.

**Comment by hirako2000** [comment]
@sasha240100 can you publish the module and close?

**Comment by sasha240100** [comment]
@sasha240100 actually yes, I need to recompile and update all modules

**Comment by hirako2000** [comment]
Closing as basic audio module is now built by `whs` project, and released a while ago.
